library(methods)
library(statmod)
library(stats)
library(graphics)
library(RCurl)
library(rjson)
library(tools)
library(utils)
library(devtools)
library(roxygen2)
library(testthat)
library(h2o)

localH2O = h2o.init()
